continuer = True
dimension_ecran = 640,480
vitesse_raquette = 10
vitesse_balle = 2,1
vitesse = 3
longueur_raquette = 60
largueur_raquette = 5
taille_balle = 10
couleur_blanc = 255,255,255
couleur_noire = 0,0,0
coordonnees_raquette_initiales = 10, int((dimension_ecran[1]-longueur_raquette)/2) #moitié de l'écran
coordonnes_balle_initiales = int(dimension_ecran[0]/2),int(dimension_ecran[1]/2)
t = 0